name: CI/CD Pipeline

on:
  push:
    branches:
      - Gningue
  pull_request:
    branches:
      - Gningue

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout du code
        uses: actions/checkout@v3

      - name:  Configuration Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.5

      - name:  Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r ./home-credit-default-risk/requirements.txt

      - name: Ajouter PYTHONPATH
        run: |
           echo "PYTHONPATH=$GITHUB_WORKSPACE/home-credit-default-risk" >> $GITHUB_ENV

      - name:  Lancer les tests Pytest
        run: |
          pytest ./home-credit-default-risk/tests/

      - name:  Vérifier le style avec flake8
        run: |
          flake8 home_credit

      - name:  Vérifier le format Black
        run: |
          black --check home_credit
